services:
  db:
    container_name: postgres-spring-boot
    image: postgres:latest
    environment:
      POSTGRES_USER: bradltr
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: engineers
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  app:
      build: .
      ports:
        - "8080:8080"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
        interval: 10s
        timeout: 5s
        retries: 5
    db:
      image: postgres:latest
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
      ports:
        - "5432:5432"
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "user"]
        interval: 10s
        timeout: 5s
        retries: 5

networks:
  db:
    driver: bridge

volumes:
  db: