name: CI Pipeline for Tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build the Application
        run: ./gradlew clean build

      - name: Validate code formatting and verify it
        run: |
          ./gradlew spotlessApply
          ./gradlew spotlessCheck

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: sleep 30

      - name: Check application health
        run: |
          for i in {1..10}; do
            curl -f http://localhost:8080/actuator/health && break || sleep 5;
          done

      - name: Run Test
        run: ./gradlew clean test -Psuite=SoftwareEngineerTestSuite_test.xml